// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/material.dart';
import 'package:flutter_application_2/main.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// import 'package:firebase_core/firebase_core.dart';
//import 'firebase_options.dart'; // Ensure this file is generated

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(UserInfo());
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUK2uBIgv9dFukGMulZoDlWt5qvl2WmjE',
    appId: '1:37363275490:web:92c11aeb2d7080b833f0bb',
    messagingSenderId: '37363275490',
    projectId: 'userinfo-92f9e',
    authDomain: 'userinfo-92f9e.firebaseapp.com',
    storageBucket: 'userinfo-92f9e.firebasestorage.app',
    measurementId: 'G-ZEHJD7QFN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSDIDfS8pnztDN86zhbn54KPbLM1wkGQ0',
    appId: '1:37363275490:android:d9ea8fa39ff354bf33f0bb',
    messagingSenderId: '37363275490',
    projectId: 'userinfo-92f9e',
    storageBucket: 'userinfo-92f9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyCVR1_wKW4FqdKoWlY32WpBhKN89Bfiw',
    appId: '1:37363275490:ios:e2e018d00247876b33f0bb',
    messagingSenderId: '37363275490',
    projectId: 'userinfo-92f9e',
    storageBucket: 'userinfo-92f9e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyCVR1_wKW4FqdKoWlY32WpBhKN89Bfiw',
    appId: '1:37363275490:ios:e2e018d00247876b33f0bb',
    messagingSenderId: '37363275490',
    projectId: 'userinfo-92f9e',
    storageBucket: 'userinfo-92f9e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUK2uBIgv9dFukGMulZoDlWt5qvl2WmjE',
    appId: '1:37363275490:web:4724e11c27c7e8d733f0bb',
    messagingSenderId: '37363275490',
    projectId: 'userinfo-92f9e',
    authDomain: 'userinfo-92f9e.firebaseapp.com',
    storageBucket: 'userinfo-92f9e.firebasestorage.app',
    measurementId: 'G-832QK42YCG',
  );
}
